services:  
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    command: postgres -c 'max_connections=600'
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./data/dbdata:/var/lib/postgresql/data:delegated
    networks:
      red:

  django:
    image: aulas2024tp:0.1
    build:
      context: ./config/django-image
    volumes:
      - ./backend/django:/usr/src/app:delegated
    environment:      
      DJANGO_SU_NAME: ${DJANGO_SU_NAME}
      DJANGO_SU_PASSWORD: ${DJANGO_SU_PASSWORD}
      DJANGO_SU_EMAIL: ${DJANGO_SU_EMAIL}
    ports:
      - 8000:8000
    networks:
      red:

networks:
  red: