services:  
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    command: postgres -c 'max_connections=600'
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./data/dbdata:/var/lib/postgresql/data:delegated
    networks:
      red:

networks:
  red:
