# Generated by Django 5.0.6 on 2024-05-29 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0003_reserva_aula_horario_materia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva_aula',
            name='id_aula',
        ),
        migrations.DeleteModel(
            name='Horario_materia',
        ),
        migrations.DeleteModel(
            name='Reserva_aula',
        ),
    ]
