# Generated by Django 5.0.6 on 2024-05-29 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0004_remove_reserva_aula_id_aula_delete_horario_materia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva_aula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fh_desde', models.DateTimeField()),
                ('fh_hasta', models.DateTimeField()),
                ('observacion', models.TextField(max_length=256)),
                ('id_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aulas.aula')),
            ],
        ),
        migrations.CreateModel(
            name='Horario_materia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fh_desde', models.DateTimeField()),
                ('fh_hasta', models.DateTimeField()),
                ('id_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aulas.materia')),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aulas.reserva_aula')),
            ],
        ),
    ]
